### ISSUE TITLE
A new name?

### ISSUE THREAD

**Issue by robinpaulson** [red-coracle/episodes#1]
It's good you've changed the App ID so it doesn't clash with the original, but perhaps we also slightly change the name as it appears to users?

Perhaps something similar, maybe "Episodic"?

Or an entirely new word, perhaps a synonym of episode?
Chapters?

Also: great to see a new release.

**Comment by red-coracle** [comment]
Thanks. Yes, I considered changing the name but hadn't come up with anything suitable yet. I'll give it some more thought.

Note that it's still a pre-release because when I was testing again just now the notifcation doesn't quite work properly. I also think I need to rework the background process for refreshing all shows because it gets killed when the device goes to sleep...

**Comment by red-coracle** [comment]
Closing in favour of #2.
