### ISSUE TITLE
Fix menu colour bug when viewing Series info

### ISSUE THREAD

**Issue by robinpaulson** [red-coracle/episodes#4]
When I am viewing a particular series and click on the "menu" button, the text is nearly the same colour as the menu background (white on very pale grey). In all other situations (overview, season), the text and background contrast: black on very pale grey.

**Comment by red-coracle** [comment]
Are you able to get a screenshot? The menu looks correct to me on all the phones/emulators I've tested.

**Comment by robinpaulson** [comment]
Yes. Before you ask why I didn't screenshot: I can't, I use Replicant, which doesn't have the binary drivers required for screenshots.

I also included a shot of the "series" screen, on which the text is easily readable.

![20191113_174506](https://user-images.githubusercontent.com/1186107/68734048-b5bc2700-063d-11ea-87b4-6fee2198f241.jpg)
![20191113_174525](https://user-images.githubusercontent.com/1186107/68734049-b654bd80-063d-11ea-805e-0bdbbef89207.jpg)

**Comment by red-coracle** [comment]
Every device/emulator I've tried always looks like this instead of popping up at the bottom and I don't know Android well enough to say why yours is different:
![image](https://user-images.githubusercontent.com/4132735/68982726-28f8a100-07d6-11ea-9ca2-6fc5a283ac30.png)


That being said, I'm think it has to do with the theme setting [here](https://github.com/red-coracle/episodes/blob/dev/app/src/main/res/layout/show_activity.xml#L40). One option would be to remove it all and have it be light-on-dark like this:
![image](https://user-images.githubusercontent.com/4132735/68982250-4298e900-07d4-11ea-890c-5e9c5c39ed18.png)

**Comment by robinpaulson** [comment]
I'm intrigued why it only happens in one menu, but not the others. I think white on black would be a good default though, it's easier on the eyes.

**Comment by blinkenlight** [comment]
I used to have this exact problem on my Galaxy SII (on 4.1.2 JB) too. I don't have it on my current Zenfone. Unfortunately I cannot test any changes as the Galaxy went bust recently, but it may have had something with it being an AMOLED phone therefore using a system-wide dark theme. The Zenfone isn't, so it doesn't use a dark theme. I also had the popping-up at the bottom thing, I can only suspect it may have had something to do with the Galaxy having physical buttons (the Zenfone doesn't do this either). To be fair though, I'm now using this fork whereas previously I was using the old app.

**Comment by robinpaulson** [comment]
Fixed with the new release! Closing
